config/routes.rb
Drugkick::Application.routes.draw do
  root to: "welcome#home"
  resources :inquiries, :except => [:index, :show]
  match 'congrats' => 'welcome#congrats', :as => :congrats

  # resources :leads

  # resources :treatment_types

  # resources :insurers

  # resources :drugs

  # resources :religions

  # resources :inquiries

  # resources :rehabs

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  geocoded_by :zip
  after_validation :geocode, :if => lambda{ |obj| obj.zip_changed? }

  has_and_belongs_to_many :drugs
  has_and_belongs_to_many :insurers
  has_and_belongs_to_many :religions
  has_and_belongs_to_many :treatment_types
  has_many :leads
  has_many :rehabs, :through => :leads

  attr_protected :ip
  attr_writer :current_step
    
  def current_step
    @current_step || steps.first
  end
    
  def steps
    %w[why location demographics drugs insurance price treatment_type religion finish]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1] 
  end

  def previous_step  
    self.current_step = steps[steps.index(current_step)-1]  
  end

  def last_step
    self.current_step = steps.last
  end  

  def first_step?  
    current_step == steps.first  
  end

  def last_step?  
    current_step == steps.last  
  end

  def all_valid?  
    steps.all? do |step|  
      self.current_step = step  
      valid?  
    end  
  end

  def num_results
    500/steps.index(current_step)
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  # GET /inquiries
  # GET /inquiries.xml
  def index
    @inquiries = Inquiry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @inquiries }
    end
  end

  # GET /inquiries/1
  # GET /inquiries/1.xml
  def show
    redirect_to new_inquiry_path
    # @inquiry = Inquiry.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.xml  { render :xml => @inquiry }
    # end
  end

  # GET /inquiries/new
  # GET /inquiries/new.xml
  def new
    session[:inquiry_params] ||= {} 
    if session[:inquiry_id]
      @inquiry = Inquiry.find(session[:inquiry_id])
    else
      @inquiry = Inquiry.new(session[:inquiry_params]) 
    end
    
    @inquiry.current_step = session[:inquiry_step]  

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inquiry }
    end
  end

  # GET /inquiries/1/edit
  def edit
    @inquiry = Inquiry.find(params[:id])
  end

  # POST /inquiries
  # POST /inquiries.xml
  def create
    logger.info params
    session[:inquiry_params].deep_merge!(params[:inquiry]) if params[:inquiry]
    if session[:inquiry_id]
      @inquiry = Inquiry.find(session[:inquiry_id])
    else
      @inquiry = Inquiry.new(session[:inquiry_params]) 
    end
    @inquiry.update_attributes(session[:inquiry_params])
    @inquiry.ip = request.remote_ip
    @inquiry.current_step = session[:inquiry_step]  
    if @inquiry.valid?
      if params[:back_button]  
        @inquiry.previous_step
      elsif params[:finish]
        @inquiry.last_step 
      else
        @inquiry.next_step  
      end  
      session[:inquiry_step] = @inquiry.current_step  
    end
    
    session[:inquiry_id] = @inquiry.id if @inquiry.save

    render 'new'

    # Railscasts code
    # if @inquiry.new_record?  
    #   render 'new'  
    # else
    #   lsession[:inquiry_step] = session[:inquiry_params] = nil  
    #   flash[:notice] = "Inquiry saved."  
    #   redirect_to @inquiry  
    # end

    # Original scaffold code
    # @inquiry = Inquiry.new(params[:inquiry])

    # respond_to do |format|
    #   if @inquiry.save
    #     format.html { redirect_to(@inquiry, :notice => 'Inquiry was successfully created.') }
    #     format.xml  { render :xml => @inquiry, :status => :created, :location => @inquiry }
    #   else
    #     format.html { render :action => "new" }
    #     format.xml  { render :xml => @inquiry.errors, :status => :unprocessable_entity }
    #   end
    # end
  end

  # PUT /inquiries/1
  # PUT /inquiries/1.xml
  def update
    logger.info params
    all_done = false
    session[:inquiry_params].deep_merge!(params[:inquiry]) if params[:inquiry]
    @inquiry = Inquiry.find(params[:id])
    @inquiry.update_attributes(session[:inquiry_params])
    @inquiry.ip = request.remote_ip
    @inquiry.current_step = session[:inquiry_step]  
    if @inquiry.valid?
      if params[:back_button]  
        @inquiry.previous_step
      elsif params[:finish]
        @inquiry.last_step 
      else
        if @inquiry.last_step?
          all_done = true
        else
          @inquiry.next_step
        end
     end
      session[:inquiry_step] = @inquiry.current_step  
    end
    @inquiry.save!
    logger.info @inquiry.current_step
    logger.info @inquiry.last_step?
    logger.info @inquiry.inspect

    if all_done
      session[:inquiry_step] = session[:inquiry_params] = nil
      redirect_to congrats_path
    else
      render 'new'
    end
    # @inquiry = Inquiry.find(params[:id])

    # respond_to do |format|
    #   if @inquiry.update_attributes(params[:inquiry])
    #     format.html { redirect_to(@inquiry, :notice => 'Inquiry was successfully updated.') }
    #     format.xml  { head :ok }
    #   else
    #     format.html { render :action => "edit" }
    #     format.xml  { render :xml => @inquiry.errors, :status => :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.xml
  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy

    respond_to do |format|
      format.html { redirect_to(inquiries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_finish_copy.html.erb
<p>You're finished! Enter your info below to get in touch with treatment experts at your recommended facilities:</p>

app/views/inquiries/_finish_step.html.erb
<%= f.input :name %>
<%= f.input :phone, input_html: {type: "text"} %>
<%= f.input :email %>
<%= f.input :message, label: "Please describe your situation in more detail",  :input_html => { :cols => 80, :rows => 10 } %>

app/views/inquiries/_insurance_copy.html.erb
<p>Almost there! Just a couple more questions and we’ll be able to match you with the best treatment options for you.</p>

app/views/inquiries/_insurance_step.html.erb
<%= f.association :insurers, :label => "Does the person in need of help have health insurance? If so, select the provider below." %>

app/views/inquiries/_location_step.html.erb
<%= f.input :zip, :label => "Enter the zip code of the person needing treatment" %>

app/views/inquiries/_price_step.html.erb
<legend>Which monthly price range is the best fit for your budget?</legend>
<% why_options = [] %>
<% why_options << ["Low", "Under $5,000"] %>
<% why_options << ["Med","Between $5,000 and $20,000"] %>
<% why_options << ["High", "Over $20,000"] %>
<%= f.collection_radio :price_range, why_options, :first, :last %>

app/views/inquiries/_religion_copy.html.erb
<p>Nice work! You’ve made it to the final question in our survey. Thank you for giving us the opportunity to help.</p>

app/views/inquiries/_religion_step.html.erb
<%= f.association :religions, :as => :check_boxes %>

app/views/inquiries/_treatment_type_copy.html.erb
<p>By matching you with the right treatment program or rehab center, we increase your chances for successful recovery.</p>

app/views/inquiries/_treatment_type_step.html.erb
<%= f.association :treatment_types, :as => :check_boxes %>

app/views/inquiries/_why_step.html.erb
<legend>What brings you here?</legend>
<% why_options = [] %>
<% why_options << ['Problem', "I know I have a problem and I'm looking for treatment"] %>
<% why_options << ['Emergency',"I've hit rock-bottom and I need help urgently"] %>
<% why_options << ['Curious', "I think I might have a problem and I'm doing some research into therapy"] %>
<% why_options << ['Court',"I was court-ordered to find a treatment program"] %>
<% why_options << ['Friend',"I'm looking for help for a friend or loved one"] %>
<%= f.collection_radio :why, why_options, :first, :last %>

app/views/inquiries/index.html.erb
<h1>Listing inquiries</h1>

<table>
  <tr>
    <th>Zip</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Repeat</th>
    <th>Price min</th>
    <th>Price max</th>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Ip</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inquiries.each do |inquiry| %>
  <tr>
    <td><%= inquiry.zip %></td>
    <td><%= inquiry.gender %></td>
    <td><%= inquiry.age %></td>
    <td><%= inquiry.repeat %></td>
    <td><%= inquiry.price_min %></td>
    <td><%= inquiry.price_max %></td>
    <td><%= inquiry.name %></td>
    <td><%= inquiry.phone %></td>
    <td><%= inquiry.email %></td>
    <td><%= inquiry.ip %></td>
    <td><%= inquiry.message %></td>
    <td><%= link_to 'Show', inquiry %></td>
    <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
    <td><%= link_to 'Destroy', inquiry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<div class="two columns">&nbsp;</div>
<div class="nine columns">
  <%= render :partial => "#{@inquiry.current_step}_copy" %>
  <div class="clear"></div>
  <%= simple_form_for(@inquiry) do |f| %>
    <%= f.error_notification %>

    <div class="inputs">
      <fieldset>
        <%= render "#{@inquiry.current_step}_step", :f => f %>
      </fieldset>
    </div>

    <div class="actions">
    <% if @inquiry.last_step? %>
      <%= f.submit "&lt; Back".html_safe, :name => "back_button" %>
      <%= f.submit 'Send Inquiry' %>
    <% else %>
      <%= f.submit "&lt; Back".html_safe, :name => "back_button" %>
      <%= f.submit 'Next Step &gt;'.html_safe %>
    <% end %>
    </div>
    <% unless @inquiry.first_step? %>
      <% if @inquiry.last_step? %>
        <p></p>
      <% else %>
        <p>We found <strong><%= @inquiry.num_results %></strong> providers that match your needs. Answer the question above for more targeted results, or you can contact them now by clicking below</p>
        <%= f.submit "Get your results now", :name => "finish" %>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="one column">&nbsp;</div>
<div class="four columns">
  <div class="social">
    <p>Know someone who needs help?<br/>Spread the word about DrugKick!</p>
    <img src="/images/social.png"/>
  </div>
  <div class="providers">
    <p>&nbsp;</p>
    <p><strong>Treatment Providers</strong></p>
    <ul class="square">
      <li>Grow your network</li>
      <li>Connect with people in need</li>
      <li>Pre-qualified matches</li>
      <li>Manage your online profile</li>
    </ul>
    <a href="#" class="button">Contact us to join our network</a>
  </div>
</div>
<div class="clear"></div>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zip:</b>
  <%= @inquiry.zip %>
</p>

<p>
  <b>Gender:</b>
  <%= @inquiry.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @inquiry.age %>
</p>

<p>
  <b>Repeat:</b>
  <%= @inquiry.repeat %>
</p>

<p>
  <b>Price min:</b>
  <%= @inquiry.price_min %>
</p>

<p>
  <b>Price max:</b>
  <%= @inquiry.price_max %>
</p>

<p>
  <b>Name:</b>
  <%= @inquiry.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @inquiry.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @inquiry.email %>
</p>

<p>
  <b>Ip:</b>
  <%= @inquiry.ip %>
</p>

<p>
  <b>Message:</b>
  <%= @inquiry.message %>
</p>


<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>